import React from 'react';
import { Header } from '../Header';

export function AboutUs() {
  return (
    <div className='about-us-page'>
      <Header pageName="About Us" />
        <h2>Our Mission</h2>
        <p>
          We are dedicated to providing accurate and up-to-date information about countries around the world.
          Our goal is to make learning about the world simple, accessible, and engaging for everyone.
        </p>
        <h2>Our Team</h2>
        <p>
          We're a passionate team of developers, designers, and data enthusiasts who believe in the power of open data and global knowledge.
        </p>
        <h2>Contact Us</h2>
        <p>
          Have questions or suggestions? Reach out to us at <a href="mailto:info@example.com">info@example.com</a>.
        </p>
        <small> Text generated by OpenAI's ChatGPT and edited by the team.</small>
    </div>
  );
}
